#!/bin/bash

set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

cd "$DIR/.."

cargo clean
cargo fmt
cargo build --all-targets
cargo test --all-targets
cargo clippy --all-targets
